# syntax=docker/dockerfile:1

# ---- base -------------------------------------------------------------------
FROM node:20-alpine AS base
WORKDIR /app
# Retry apk's package fetch a few times — Alpine's CDN occasionally returns a
# transient TLS/connection error on CI runners; a bare `apk add` has no
# retry logic of its own and fails the whole build on the first flake.
RUN for i in 1 2 3 4 5; do \
      apk add --no-cache libc6-compat openssl && break; \
      echo "apk add failed (attempt $i/5), retrying in 5s..." && sleep 5; \
    done

# ---- deps --------------------------------------------------------------------
# NOTE: no package-lock.json is committed yet (see README "Getting Started"),
# so this uses `npm install` rather than `npm ci`. Once a lock file exists
# (generated by the first `npm install` a developer runs), switch this back
# to `npm ci` for reproducible, cached installs — the same tradeoff already
# documented in .github/workflows/ci.yml.
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm install

# ---- development ---------------------------------------------------------
# Used by docker-compose for local dev: source is bind-mounted, so this stage
# only needs dependencies installed; `npm run dev` runs against live-mounted code.
FROM deps AS development
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["npm", "run", "dev"]

# ---- build -------------------------------------------------------------------
FROM deps AS build
COPY . .
RUN npx prisma generate
RUN npm run build

# ---- production ----------------------------------------------------------
FROM base AS production
ENV NODE_ENV=production
RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=build /app/public ./public
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma

USER nextjs
EXPOSE 3000
ENV PORT=3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1
CMD ["node", "server.js"]
