# syntax=docker/dockerfile:1

# ---- base -------------------------------------------------------------------
FROM node:20-alpine AS base
WORKDIR /app
# Retry apk's package fetch a few times — Alpine's CDN occasionally returns a
# transient TLS/connection error on CI runners; a bare `apk add` has no
# retry logic of its own and fails the whole build on the first flake.
RUN for i in 1 2 3 4 5; do \
      apk add --no-cache libc6-compat openssl && break; \
      echo "apk add failed (attempt $i/5), retrying in 5s..." && sleep 5; \
    done

# ---- deps --------------------------------------------------------------------
# NOTE: no package-lock.json is committed yet (see README "Getting Started"),
# so this uses `npm install` rather than `npm ci`. Once a lock file exists
# (generated by the first `npm install` a developer runs), switch this back
# to `npm ci` for reproducible, cached installs — the same tradeoff already
# documented in .github/workflows/ci.yml.
#
# package.json's `postinstall` script runs `prisma generate`, which requires
# prisma/schema.prisma to already be present — so that file must be copied
# in BEFORE `npm install` runs, not just the two package manifests.
FROM base AS deps
COPY package.json package-lock.json* ./
COPY prisma/schema.prisma ./prisma/schema.prisma
RUN npm install

# ---- development ---------------------------------------------------------
# Used by docker-compose for local dev: source is bind-mounted, so this stage
# only needs dependencies installed; `npm run dev` runs against live-mounted code.
FROM deps AS development
COPY . .
RUN npx prisma generate
EXPOSE 3000
CMD ["npm", "run", "dev"]

# ---- migrator ------------------------------------------------------------
# Used for one-off ECS tasks that need the Prisma CLI and/or `npm run
# db:seed` (which requires `tsx`, a devDependency) — the `production`
# target below intentionally strips both, since the long-running app
# server itself only ever calls the Prisma *client* (already vendored into
# .next/standalone via node_modules/.prisma), never the CLI. Keeping this
# as its own stage (rather than reusing `build`) avoids needing to run
# `next build` just to run a migration or seed script.
FROM deps AS migrator
COPY . .
RUN npx prisma generate
CMD ["npx", "prisma", "migrate", "deploy"]

# ---- build -------------------------------------------------------------------
# `next build`'s "Collecting page data" step imports every route module to
# determine its runtime, which transitively imports src/lib/env.ts — whose
# Zod schema requires DATABASE_URL to be a non-empty string (see that
# file). No real database connection is ever made at build time (nothing
# here runs a query), so a syntactically-valid placeholder is sufficient;
# this ARG/ENV pair exists ONLY in this build stage's image layer and is
# never copied into the `production` stage below (COPY --from=build only
# copies specific file paths, never environment variables), so the real
# runtime DATABASE_URL (injected via Secrets Manager in production — see
# infra/aws/terraform/ecs.tf) is what the running container actually uses.
FROM deps AS build
ARG DATABASE_URL=postgresql://build:build@localhost:5432/build
ENV DATABASE_URL=${DATABASE_URL}
COPY . .
RUN npx prisma generate
RUN npm run build

# ---- production ----------------------------------------------------------
FROM base AS production
ENV NODE_ENV=production
RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=build /app/public ./public
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma

USER nextjs
EXPOSE 3000
ENV PORT=3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1
CMD ["node", "server.js"]
