# ------------------------------------------------------------------------------
# S3 bucket for restaurant/product images (backs StorageProvider's "s3" mode,
# see src/modules/storage/storage-provider.ts). Uploads go directly from the
# browser to S3 via short-lived presigned PUT URLs generated by the app
# (never proxied through the app server) — see /api/storage/presign. Reads
# are served through the CloudFront distribution defined in cdn.tf, not
# directly from the bucket, so images benefit from edge caching and the
# bucket itself can stay fully private.
# ------------------------------------------------------------------------------

resource "random_id" "media_bucket_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "media" {
  bucket = "${local.name_prefix}-media-${random_id.media_bucket_suffix.hex}"

  tags = { Name = "${local.name_prefix}-media" }
}

resource "aws_s3_bucket_public_access_block" "media" {
  bucket = aws_s3_bucket.media.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "media" {
  bucket = aws_s3_bucket.media.id
  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_versioning" "media" {
  bucket = aws_s3_bucket.media.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "media" {
  bucket = aws_s3_bucket.media.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Browsers PUT directly to this bucket using the presigned URL the app
# generates — that request originates from the customer's/restaurant
# owner's browser at whatever origin the app is served from, so CORS must
# allow it explicitly (S3 does not consider a presigned URL's signature a
# substitute for a CORS check on cross-origin browser requests).
resource "aws_s3_bucket_cors_configuration" "media" {
  bucket = aws_s3_bucket.media.id

  cors_rule {
    allowed_methods = ["PUT", "GET"]
    allowed_origins = local.app_origins
    allowed_headers = ["*"]
    max_age_seconds = 3600
  }
}

# Only CloudFront (via Origin Access Control) may read objects — the bucket
# itself is not publicly reachable at its S3 URL.
data "aws_iam_policy_document" "media_bucket_policy" {
  statement {
    sid    = "AllowCloudFrontServicePrincipalReadOnly"
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["cloudfront.amazonaws.com"]
    }

    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.media.arn}/*"]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceArn"
      values   = [aws_cloudfront_distribution.media.arn]
    }
  }
}

resource "aws_s3_bucket_policy" "media" {
  bucket = aws_s3_bucket.media.id
  policy = data.aws_iam_policy_document.media_bucket_policy.json
}

resource "aws_cloudfront_origin_access_control" "media" {
  name                              = "${local.name_prefix}-media-oac"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}
